remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

title: Alan Muniz
description: Engenheiro de Dados | Python, Spark, AWS, Airflow, Power BI
show_downloads: false

author:
  name: Alan Muniz
  linkedin: https://br.linkedin.com/in/alan-b-muniz-540b7a91
  email: alan.abm.ti@gmail.com

markdown: kramdown
